### ISSUE TITLE
Exclude closed boards

### ISSUE THREAD

**Issue by StevenVerbiest** [janhenckens/alfredapp-trello#18]

**Comment by littke** [comment]
+1

**Comment by littke** [comment]
(This doesn't work still, correct?)

**Comment by janhenckens** [comment]
Hey @littke, that's correct. 

We stopped using Trello at the office so development of this workflow has taken a bit of a back seat. 
I'll add it to next week's list and I'll get back to you.

**Comment by littke** [comment]
Ahh, thanks so much -- appreciate it!

**Comment by littke** [comment]
(What are you guys using instead?)

**Comment by janhenckens** [comment]
We went to Jira because it offers a more fixed and structured workflow for issues. Still using Trello for some overal project management though, but with only a few boards so search is much less needed these days.

Can I ask if you're running Alfred 2 or the new Alfred 3?

**Comment by littke** [comment]
3

**Comment by janhenckens** [comment]
That could cause some issues as well, the paths for cache and storage are hard coded to Alfred 2 right now. I'll definitely try and fix that asap!

**Comment by littke** [comment]
Thanks so much!!

**Comment by janhenckens** [comment]
I released a version that has Alfred 3 compatibility, you can find that here: https://github.com/janhenckens/alfredapp-trello/releases/tag/v1.4.0

As for the closed boards, that's a bit harder as i'm not calling the API for every query (that would make the extension to slow to be useful). Currently looking into ways to update the local date periodically but I wouldn't hold my breath for this to be added soon :)
